dataset:
  name: Peptides-func
  encoding: False
pos_encoding:
  type: RWPE
  walk_length: 21
training:
  seed: 42
  total_epochs: 250
  warmup_epochs: 5
  coarsening: False
model:
  hidden_channels: 235
  out_channels: 10
  num_layers: 6
  act: gelu
  dropout: 0.1
  norm: batch
  lr: 0.001
mlp:
  dropout: 0.1
  L: 3