dataset:
  name: Peptides-func
  encoding: False
pos_encoding:
  type: RWPE
  walk_length: 21
training:
  seed: 42
  total_epochs: 250
  warmup_epochs: 5
  coarsening: True
coarsening:
  num_layers_before: 2
  num_layers_after: 3