dataset:
  name: Peptides-struct
  pos_encoding: False
pos_encoding:
  type: LAPE
  num_eigenvectors: 3
training:
  seed: 42
  total_epochs: 250
  warmup_epochs: 5
  coarsening: False
  log_directory: ./training_logs
model:
  hidden_channels: 235
  num_layers: 6
  act: gelu
  dropout: 0.1
  norm: batch
  lr: 0.001
mlp:
  dropout: 0.1
  L: 3